import type { Metadata } from 'next'
import { Raleway, Great_Vibes } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar/Navbar'
import { ThemeProvider } from '@/providers/theme-provider'

const raleway = Raleway({ subsets: ['latin'] })

const greatVibes = Great_Vibes({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-greatVibes'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${greatVibes.variable} ${raleway.className}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <Navbar />
            {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
