import type { Metadata } from 'next'
import { Raleway, Great_Vibes } from 'next/font/google'
import './globals.css'

const raleway = Raleway({ subsets: ['latin'] })

const greatVibes = Great_Vibes({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-greatVibes'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${greatVibes.variable} ${raleway.className}`}>
        {children}
      </body>
    </html>
  )
}
